---

- name: A playbook to install Kubectl
  hosts: localhost
  user: ubuntu
  become: yes

  vars:
    myPath: /home/ubuntu/cw2

  tasks:
  - name: 1. Update APT Package Manager
    apt:
     update_cache: yes

  - name: 2. Install Kubectl dependency Packages
    apt:
     name={{ item }}
    with_items:
     - apt-transport-https

  - name: 3. Get APT Key
    shell:
     cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg
      | sudo apt-key add -

  - name: 4. Get Kubernetes URL
    shell:
     cmd: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main"
      | sudo tee -a /etc/apt/sources.list.d/kubernetes.list

  - name: 5. Update Package Manager
    apt:
     update_cache: yes

  - name: 6. Install Kubectl Packages
    apt:
     name={{ item }}
    with_items:
     - kubectl
